#!/bin/zsh
# joe prompt theme
GITDIR=${GITDIR:-~/git}
ZSH_GIT_DIR=$GITDIR/zsh-git/

prompt_joe_help () {
  cat <<'EOF'
  General Look

  Non-root users:
  [24:00:00] user@host /path	[jobs: 1]
   %

  root:
  [24:00:00] host /path   	 [jobs: 1]
   %
  
  This prompt is color-scheme-able.  You can invoke it thus:

  prompt joe [<color1> [<color2> [<color3> [<color4> [<color5>]]]]]
  	color1: user@host (non-root user)
	color2: [24:00:00] (time)
	color3: /path/ (pwd)
	color4: [jobs: 1] (jobcount in right prompt)
	color5: host (like user@host but for root)

EOF
}

prompt_joe_setup () {
	setopt prompt_subst
    typeset -gA ZSH_JOE_COLORS

	source $ZSH_GIT_DIR/git/init_git_prompt.sh

    : ${ZSH_JOE_COLORS[user]:="red"}
    : ${ZSH_JOE_COLORS[time]:="cyan"}
    : ${ZSH_JOE_COLORS[pwd]:="blue"}
    : ${ZSH_JOE_COLORS[jobs]:="green"}
    : ${ZSH_JOE_COLORS[root]:="magenta"}
	
	local userstr
	local usercol
	if [ "$USER" = 'root' ]
	then
	  userstr="%F{$ZSH_JOE_COLORS[root]}%m"
	  usercol=$ZSH_JOE_COLORS[root]
	else
	  userstr="%F{$ZSH_JOE_COLORS[user]}%n@%m"
	  usercol=$ZSH_JOE_COLORS[user]
	fi

	# main prompt
	PROMPT="%F{$ZSH_JOE_COLORS[time]}[%*] $userstr%b%B"'${git_info}'"%B%F{$ZSH_JOE_COLORS[pwd]} %~$prompt_newline %% %b%k%f"

	# sub prompt (e.g. "for> ")
	PROMPT2="%F{$usercol}%_%F{$ZSH_JOE_COLORS[pwd]}> %b%k%f"

	# right prompt, shows number jobs and :( if the last exit status was not 0
	RPROMPT="%(?..%B:(%b) %B%F{$ZSH_JOE_COLORS[jobs]}%1(j.[jobs: %j]%b"
}

prompt_joe_setup "$@"
